### ISSUE TITLE
[BUG] Role conflict trying to deploy second DHF instance to ML Host with current Envision and DHF instance

### ISSUE THREAD

**Issue by sjordan1975** [marklogic-community/data-hub-central-community#209]
*### Welcome Data Hub Central Community Edition(DHCCE) enthusiast!

Let's get the most out of this ticket, please fill out this template.

#### The issue

Short description of the problem:

Attempting to deploy additional instance of DHF to a ML host that is currently hosting an instance of DHF and Envision throws a 500 error complaining of a role conflict

What behavior are you expecting?

I should be able to run multiple instances of Envision and DHF each against their own databases on the same ML host.

What are the steps to reproduce the issue:
1) In a folder (ex. project_a) drop a dhf war file, start QS and deploy
2) Then in same folder drop Envision war and run
3) Enjoy Envision
4) In another folder (ex. project_b) drop a dhf war file
5) Either using QS or alternatively gradle *try* to deploy new DHF with appropriately named ports and db name different from those used in Project A
6) Enjoy your crash

#### Tech details

Which Operating System are you using?
OSX 10.13.6

Which version of MarkLogic are you using?
10.0-5

Which version of the Data Hub are you using?
5.2.4

NB. Also verified error on windows 10 using DHF 5.4.0

#### The devil is in the details...

See attached files

[gradle debug.log](https://github.com/marklogic-community/data-hub-central-community/files/6154257/gradle.debug.log)

[formatted 8002_ErrorLog.txt](https://github.com/marklogic-community/data-hub-central-community/files/6154258/formatted.8002_ErrorLog.txt)

[dhf-envision-error.txt](https://github.com/marklogic-community/data-hub-central-community/files/6154139/dhf-envision-error.txt)

**Comment by wpaven** [comment]
Thank you for logging this and for all the logs. 

Did you set different application.properties for the second envision? And I'm assuming you dropped this second envision.jar in the project_b folder and ran from there? ( In your steps above I don't see in 4-6 where the 2nd envision is started so just want to confirm it's there.)

**Comment by sjordan1975** [comment]
Hi @wpaven 

There is no second envision. The process won't allow us to get that far.

Trying to get the second DHF stood up (either through QuickStart or gradle) gives the reported error

**Comment by wpaven** [comment]
ok. thank you for confirming.

**Comment by wpaven** [comment]
@sjordan1975 Try setting mlDeployWithCma=false in gradle.properties then run mldeploy for the second instance.

**Comment by sjordan1975** [comment]
@wpaven 

Setting mlDeployWithCma=false seems to have done the trick. What does disabling cma do under the hood as relates to the deployment process, roles, privs, etc?

Is setting mlDeployWithCma=false the recommended process to allow mupltiple DHF and Envision instances on the same ML host? Something that should be captured in a README? 

Or is it just a workaround?

As an aside, after getting the second DHF instane up, I dropped the Envision war into the folder and fired up Envision. Things _seem_ to be working, but the UI doesn't give any indication of which DHF (set of databases) it's pointing to.

In fact, if you click on the Admin link from the upper righthand menu, you see the following language:

>Press the reset button to delete documents created while demonstrating. This button clears the Jobs database but does not delete any documents in data-hub-STAGING/FINAL that are assiciated with entity services, flows, steps etc.

Which suggests it's pointing to data-hub-* set of databases, when in my DHF2 instance, I renamed everything data-hub-2-*

This language might just be a small oversight in the UI where it's hardcoded, rather than dynamic.

**Comment by wpaven** [comment]
@sjordan1975  Thanks again! 
The CMA flag has to do with CMA and DHF is recommended when you use custom roles.  See comments on https://github.com/marklogic-community/data-hub-central-community/issues/210#issuecomment-802266460 

I'm going to have to look into the UI issue and what's actually being queried.   Sounds like you see the right data, but just the UI is misleading?

**Comment by sjordan1975** [comment]
@wpaven 

>I'm going to have to look into the UI issue and what's actually being queried. Sounds like you see the right data, but just the UI is misleading?

I didn't load any data into the second instance of DHF, so can't say for sure everything works as expected, but other than the language on the Admin page, the appearance is that things are working -- it did at least deploy :)

**Comment by xmlnovelist** [comment]
Per comments, this issue was solved with the proper settings.
