### ISSUE TITLE
[BUG] Gradle mlDeploy results in error after DHCCE module install

### ISSUE THREAD

**Issue by awanczowski** [marklogic-community/data-hub-central-community#210]
*### Welcome Data Hub Central Community Edition(DHCCE) enthusiast!

Let's get the most out of this ticket, please fill out this template.

#### The issue

Short description of the problem:
Running a mlDeploy after  the DHCCE modules have been installed result in an error

```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':hubDeploySecurity'.
> 500 Internal Server Error: [{"errorResponse":{"statusCode":"500", "status":"Internal Server Error", "messageCode":"CMA-ERRORCONFIG", "message":"CMA-ERRORCONFIG (err:FOER0000): MANAGE-CONFLICTINGCONFIGerr:FOER00001.0-mlA conflict... (7886 bytes)]
```

What behavior are you expecting?

What are the steps to reproduce the issue:
1) Do an initial install of DHF using mlDeploy
2) Run the DHCCE jar to start and install modules
3) Run another mlDeploy after DHCCE install is completed

#### Tech details

Which Operating System are you using? CentOS

Which version of MarkLogic are you using? 10.0-6.1

Which version of the Data Hub are you using? 5.2.6

**Comment by awanczowski** [comment]
The resolution to the issue is to disable CMA. This can be done by adding `mlDeployWithCma=false` to the gradle properties.

**Comment by rjrudin** [comment]
Adding some color here - CMA doesn't handle deploying URI privileges well. The issue arises from Envision adding Envision-specific roles to 2 of the DHF privileges, which is a perfectly reasonable thing to do. But CMA throws an error on this, while RMA does not. So disabling CMA usage in DHF for privileges fixes the problem.

**Comment by wpaven** [comment]
thanks @awanczowski and @rjrudin

**Comment by xmlnovelist** [comment]
Closing this because it's not an Envision bug. As @rjrudin commented, the bug is with cma.
