### ISSUE TITLE
[BUG] Pipes Compatabilty.

### ISSUE THREAD

**Issue by wpaven** [marklogic-community/data-hub-central-community#245]
*### Welcome Data Hub Central Community Edition(DHCCE) enthusiast!

Let's get the most out of this ticket, please fill out this template.

#### The issue

In HC the format and directory structure of .json artifacts has changed.  Pipes doesn't see custom steps available to overwrite by default anymore. Manual editing required.  And HC doesn't allow you to create custom steps anymore with the UI (only manually or using gradle).  In CE we can create the custom step, but the sourceCollection and sourceQuery attributes have to be added manually to a different file for Pipes to pick them up.

So...

.  The pipes java code DOES NOT read the steps/custom/<step_name>.step.json file first to pick up the sourceCollection and sourceQuery values.  As such, they NEED TO BE PLACED IN the options property in step-definitions/custom/<step_name>/<step_name>.step.json, e.g.,
    {
        ...
        “options” : {
            “sourceCollection” : “CC-BrandA-Customers.csv”,
            “sourceQuery” : “cts.collectionQuery([\“CC-BrandA-Customers.csv\“])”
        },
        ...
    }

If we do this update in CE, then user can create a custom step in CE and select in Pipes for deployment/overwrite.

Short description of the problem:

What behavior are you expecting?

What are the steps to reproduce the issue:
1)
2)
3)

#### Tech details

Which Operating System are you using?

Which version of MarkLogic are you using?

Which version of the Data Hub are you using?

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  `java -jar dhcce.jar -d > myoutput.txt`

**Comment by xmlnovelist** [comment]
Fixed in 5.5.3.
