### ISSUE TITLE
[BUG] Deletion of one Step in the workflow deletes all the steps

### ISSUE THREAD

**Issue by radaniba** [marklogic-community/data-hub-central-community#247]
Hi,

I noticed that deleting a step in the workflow deletes all the steps

![image](https://user-images.githubusercontent.com/1666443/117934453-48be4600-b335-11eb-95be-414aca7fb14b.png)

I used the delete step button on the UI

Rad

**Comment by wpaven** [comment]
What version are you using sir?  I just created a new flow with 5.4.2.  Added two mapping steps. Did some mapping.  Deleted the second step, and the first step was retained as it should be.

Do you have some additional detail you can provide to help me to recreate the problem please?

**Comment by radaniba** [comment]
I apologize @wpaven as follow up I did an entire upgrade to my systems and several things are now resolved

**Comment by wpaven** [comment]
Excellent. Thank you!
