### ISSUE TITLE
[BUG] Navigational top bar overlaps content on some pages

### ISSUE THREAD

**Issue by larsw** [marklogic-community/data-hub-central-community#281]
#### The issue

Short description of the problem:
![dhcce-ui-problem](https://user-images.githubusercontent.com/63235/136399245-82e27368-89df-467e-af05-11dd46511e44.png)
Re. the screenshot. The top nav bar overlaps the content of the page.

What behavior are you expecting?

What are the steps to reproduce the issue:
1) Pull and run the latest MarkLogic HR360 image from Docker Hub
2) Open and login to the DHCCE.
3) Navigate to the Integrate page.

#### Tech details

Which Operating System are you using?
Ubuntu 20.04

Which version of MarkLogic are you using?
store/marklogicdb/marklogic-hr360-datahub:5.5.3

Which version of the Data Hub are you using?
As bundled in the Docker image mentioned

Same behavior in both Chrome 94.0 and Firefox 92.0

**Comment by xmlnovelist** [comment]
Thank you. I see this.

**Comment by xmlnovelist** [comment]
This fixed in 5.6.0
